---
externalId: tr-create_asset_hierarchy
name: create_asset_hierarchy
query:
    file: transformation.sql
destination:
    type: asset_hierarchy
ignoreNullFields: true
shared: true
action: upsert
dataSetExternalId: src:001:sap:ds
authentication:
    clientId: ${COGNITE_CLIENT_ID}
    clientSecret: ${COGNITE_CLIENT_SECRET}
    tokenUrl: https://login.microsoftonline.com/16e3985b-ebe8-4e24-9da4-933e21a9fc81/oauth2/v2.0/token
    cdfProjectName: ${CDF_PROJECT_NAME}
    scopes:
        - https://westeurope-1.cognitedata.com/.default
