---
#######################################
# AUTHENTICATION OPTION 1:            #
#                          Using OIDC #
#######################################
name: Deploy transformations

on:
    push:
        branches: [main]
        # branches: [none]

jobs:
    deploy:
        name: Deploy transformations
        runs-on: ubuntu-latest
        strategy:
            matrix:
                environment: [test, prod]
                include:
                    - environment: test
                      # CDF cluster, like bluefield, greenfield or westeurope-1
                      CDF_CLUSTER: westeurope-1
                      # CDF Project name
                      CDF_PROJECT: cdf-bootcamp-13-test
                      # Azure AD tenant id
                      IDP_TENANT: 16e3985b-ebe8-4e24-9da4-933e21a9fc81
                    - environment: prod
                      # CDF cluster, like bluefield, greenfield or westeurope-1
                      CDF_CLUSTER: westeurope-1
                      # CDF Project name
                      CDF_PROJECT: cdf-bootcamp-13-prod
                      # Azure AD tenant id
                      IDP_TENANT: 16e3985b-ebe8-4e24-9da4-933e21a9fc81

        environment: ${{ matrix.environment}}
        env:
            CDF_HOST: https://${{ matrix.CDF_CLUSTER }}.cognitedata.com/
            # Credentials to be used when running your transformations,
            # as referenced in your manifests
            COGNITE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
            COGNITE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            CDF_PROJECT_NAME: ${{ matrix.CDF_PROJECT }}

        steps:
            - uses: actions/checkout@v2
            - uses: cognitedata/transformations-cli@main
              with:
                  path: config/transformations
                  client-id: ${{ secrets.CLIENT_ID }}
                  client-secret: ${{ secrets.CLIENT_SECRET }}
                  cdf-project-name: ${{ matrix.CDF_PROJECT }}
                  token-url: https://login.microsoftonline.com/${{ matrix.IDP_TENANT }}/oauth2/v2.0/token
                  scopes: ${{ env.CDF_HOST }}.default
                  cluster: ${{ matrix.CDF_CLUSTER }}
